version: '3.7'
services:
  document:
    build: api/document/.
    container_name: document
    ports:
      - "5550:5550"
    environment: 
      BASE_URL : ":5550"
      ConnectionString: "document-db:26257"
      DatabaseName: docman
      DbUserName: docmanuser
      DbPassword: docmanpassword
    networks:
      - docman-network
    depends_on:
      - document-db
  document-db:
    image: cockroachdb/cockroach:latest
    container_name: document-db
    hostname: document-db
    ports:
      - 26257:26257
      - 8080:8080
    environment:
      COCKROACH_DATABASE: docman
      COCKROACH_USER: docmanuser
      COCKROACH_PASSWORD: docmanpassword
    command: start-single-node
    networks:
      - docman-network
    volumes:
      - ./api/database/document:/docker-entrypoint-initdb.d
      - documentdbdata:/cockroach/cockroach-data"
networks:
  docman-network:
    driver: bridge
volumes:
  documentdbdata:
