version: '3.7'
services:
  docman:
    build: .
    container_name: docman
    ports:
      - "5550:5500"
    environment: 
      BASE_URL : ":5550"
      JAEGER_AGENT_HOST : "jaeger"
      JAEGER_AGENT_PORT : 6831
      JAEGER_SERVICE_NAME: docman
      ConnectionString: "arangodb://{username}:{password}@mongo:27017"
      DatabaseName: docman
      DbUserName: root
      DbPassword: password
    networks:
      - docman-network      
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: docman_jaeger
    ports: 
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - docman-network      
  prometheus:
    build: prometheus/.
    container_name: docman_prometheus
    networks:
      - docman-network    
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on: 
      - prometheus  
    networks:
      - docman-network      
  arangodb:
    image: arangodb/arangodb:3.10.0
    ports:
      - 8529:8529
    environment:
      ARANGO_ROOT_PASSWORD: password
    volumes:
      - ./arangodump:/docker-entrypoint-initdb.d/dumps/docman
      - dbdata:/var/lib/arangodb3
networks:
  docman-network:    
volumes:
  dbdata:
  grafana-storage: