version: '3'

tasks:
  build:
    cmds:
      - GOOS=js GOARCH=wasm go build -o  static/docman.wasm ./adapters/comm/wasm/*
    silent: true
  deploy-simple:
    cmds:
      - docker compose -f docker-compose-dev.yaml -p docman up -d --build --remove-orphans
    silent: true
  deploy-whole:
    cmds:
      - docker compose -f docker-compose.yaml -p docman up -d --build --remove-orphans
    silent: true
  stop-simple:
    cmds:
      - docker compose -f docker-compose-dev.yaml -p docman down
    silent: true
  stop-whole:
    cmds:
      - docker compose -f docker-compose.yaml -p docman down
    silent: true